name: Compilation Homebrew 3DS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Package du jeu
      run: |
        sudo apt-get update && sudo apt-get install -y zip
        # On entre dans le dossier où sont tes fichiers pour faire le zip
        cd .github/workflows
        zip -r ../../game.love main.lua config.lua game.json
        cd ../..

    - name: Build 3DS (.cia)
      uses: TurtleP/lovepotion-action@v2
      with:
        argument: 'game.love'

    - name: Telechargement du CIA
      uses: actions/upload-artifact@v4
      with:
        name: MonJeu3DS-CIA
        path: |
          *.cia
